### ISSUE TITLE
init(coder aDecoder:NSCoder) crashing with EXC_BAD_ACCESS(code=2) on XCode 6.4

### ISSUE THREAD

**Issue by lovince** [mbogh/NibDesignable#10]
My custom view from NibDesignable is crashing on *line 64* of __NibDesignable.swift__
```swift
    // MARK: - NSCoding
    required public init(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)  // line 64
        self.setupNib()
    }
```

with __EXC_BAD_ACCESS(code=2)__ when the view gets instantiated at run time. Placing breakpoints on the line suggests an infinite loop of sorts where the initializer gets called over and over again.

I am currently debugging in a bare project and have also stripped my custom class to a bare skeleton as:

```swift
import UIKit
import NibDesignable

class CustomView: NibDesignable {
}
```

Any ideas?

**Comment by lovince** [comment]
Nevermind! I found the issue.

I had set the top level view in Xib as __CustomView__ instead of a standard __UIView__!

**Comment by lovince** [comment]
Worth a highlight in the Readme.

**Comment by mbogh** [comment]
@lovince could you provide a sample project showcasing this?
Would like to see it.

Also which Xcode version are you using?
