### ISSUE TITLE
The live rendering will not work if NibDesignable is installed by CocoaPods

### ISSUE THREAD

**Issue by WhaleWatching** [mbogh/NibDesignable#11]
XCode will says `warning: IB Designables: Ignoring user defined runtime attribute for key`.

I founded that before I get crazy, please add it to README.

**Comment by mbogh** [comment]
@WhaleWatching 

What is your setup?
Xcode 6/7?

**Comment by WhaleWatching** [comment]
XCode 6

**Comment by mbogh** [comment]
Can you share your project?

I just tried using NibDesignable via CocoaPods in a new project and it works.

I had to add `@IBDesignable` on my custom class as well like shown below..

``` swift
import UIKit
import NibDesignable

@IBDesignable
class TestView: NibDesignable {

}
```

**Comment by WhaleWatching** [comment]
Maybe I didn't add the `@IBDesignable`, it's ok in put `NibDesignable.swift` to my project way without the `@IBDesignable`

**Comment by WhaleWatching** [comment]
Sorry this mistake is mine, and the `File's Owner` thing should be highlighted, for starter, it cases uncaughtable `exc_bad_access code=2` error...

**Comment by mbogh** [comment]
It is already there in the README.md
https://github.com/mbogh/NibDesignable#usage

**Comment by mbogh** [comment]
I'm closing this issue since it has been 26 days since last activity.
