### ISSUE TITLE
I copied the class NibDesignable and change the superclass to UIControl finally named it NibDesignableControl and connected actions failed

### ISSUE THREAD

**Issue by WhaleWatching** [mbogh/NibDesignable#12]
Just like title, CustomControl is subclass of NibDesignableControl, and in storyboard I connect the "Touch Up Insede" of CustomControl to viewcontroller, the action doesn't fired.

Sorry I'm a starter, can you write a works fine NibDesignableControl for UIControl? Thanks

**Comment by mbogh** [comment]
@WhaleWatching if you grab 2.1.0 thanks to @illaz you can now use `NibDesignableControl`.

Have a nice day.

**Comment by WhaleWatching** [comment]
thanks.
