### ISSUE TITLE
Call for contributors

### ISSUE THREAD

**Issue by sebastianludwig** [mbogh/NibDesignable#33]
Hey @mbogh, how about adding more maintainers to the project? You've collected nearly 200 stars, now would be a great time to add more people to ensure it's development doesn't stale. Maybe @farzadshbfn, @ggrana or @Jachobsen are interested?

Would love to see this lib being actively maintained!

**Comment by mbogh** [comment]
@sebastianludwig I'm open to that, I know I have neglected this project for a while now. But have been super busy at my fulltime job 😸 

So are anyone up for the "challenge"?

**Comment by farzadshbfn** [comment]
Well, that's awesome ✌🏼

**Comment by sebastianludwig** [comment]
Is that an "I am" @farzadshbfn? :-)

**Comment by farzadshbfn** [comment]
🤔... you're right it's not obvious... I am 😁

**Comment by mbogh** [comment]
There you go @farzadshbfn, if you are at WWDC ping me and lets meet up :)

**Comment by farzadshbfn** [comment]
Unfortunately I'm not 😞

**Comment by mbogh** [comment]
Should we close this now that @farzadshbfn is onboard?
