### ISSUE TITLE
ProfileAvatarView stays blank in demo project

### ISSUE THREAD

**Issue by nico75005** [mbogh/NibDesignable#47]
I downloaded the demo project and run it. On the device/simulator it works fin but when I open the Storyboard, the view stays blank.

In the identity inspector, `Designables` is always `Updating`.

Does it happen to someone else?

I haven't touched anything on the project.

**Comment by farzadshbfn** [comment]
Which Xcode version you're using? most of the time this is caused because of xCode, it happens with @IBDesignables mostly

**Comment by nico75005** [comment]
I'm using xcode 8.
