### ISSUE TITLE
How does it work with UITableViewCell

### ISSUE THREAD

**Issue by nico75005** [mbogh/NibDesignable#48]
I have a `UITableViewCell` that I would like to make Designable. How can I do?

Because as soon as I extend `NibDesignable`, it obviously stops being a `UITableViewCell`.

**Comment by farzadshbfn** [comment]
Well There are classes defined in the file that you can use, for instance `NibDesignableTableViewCell`

**Comment by nico75005** [comment]
Yes indeed, I realised the existence of `NibDesignableTableViewCell` later on. Sorry about that.
