### ISSUE TITLE
Designable UITableViewCell

### ISSUE THREAD

**Issue by pak-amsiq** [mbogh/NibDesignable#53]
Hello everyone. 

I'm struggling with @IBDesignable UITableViewCells. 

When I create a tableViewCell, it 's possible to change the background color of the cell to red:

![screen shot 2017-03-27 at 15 54 11](https://cloud.githubusercontent.com/assets/25478327/24359796/b277a08e-1305-11e7-9ebb-0eaa800b454a.png)
![screen shot 2017-03-27 at 15 54 18](https://cloud.githubusercontent.com/assets/25478327/24359788/ad4924fc-1305-11e7-9477-a883c8750b23.png)

But I can't see my label, and I can't update the text of the label. 

Could someone make an example for at custom table view cell with a label, or explain how to update my custom designable table view cell? 

Thank you!

**Comment by farzadshbfn** [comment]
why do you have a NibDesignable view, then a cell inside it?

**Comment by farzadshbfn** [comment]
How to design `UITableViewCells` is well explained in readme and also in #21 .
Here's also a sample of how to create [tableViewCells](https://github.com/mbogh/NibDesignable/issues/21#issuecomment-211504720)

**Comment by pak-amsiq** [comment]
Perfect, i got it to work. Thank you!
